apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Updated through the CI/CD validation branch.
resources:
  - service.yaml
  - deployment.yaml
namespace: default
images:
  - name: backend
    newName: 402282685369.dkr.ecr.us-east-1.amazonaws.com/backend
    newTag: 1657f13
